/* Auto-generated by genmsg_cpp for file /home/robotics/ros_ws/crazyflie/msg/MotorData.msg */
#ifndef CRAZYFLIE_MESSAGE_MOTORDATA_H
#define CRAZYFLIE_MESSAGE_MOTORDATA_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace crazyflie
{
template <class ContainerAllocator>
struct MotorData_ {
  typedef MotorData_<ContainerAllocator> Type;

  MotorData_()
  : header()
  , m1(0)
  , m2(0)
  , m3(0)
  , m4(0)
  {
  }

  MotorData_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , m1(0)
  , m2(0)
  , m3(0)
  , m4(0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef int32_t _m1_type;
  int32_t m1;

  typedef int32_t _m2_type;
  int32_t m2;

  typedef int32_t _m3_type;
  int32_t m3;

  typedef int32_t _m4_type;
  int32_t m4;


  typedef boost::shared_ptr< ::crazyflie::MotorData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::crazyflie::MotorData_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct MotorData
typedef  ::crazyflie::MotorData_<std::allocator<void> > MotorData;

typedef boost::shared_ptr< ::crazyflie::MotorData> MotorDataPtr;
typedef boost::shared_ptr< ::crazyflie::MotorData const> MotorDataConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::crazyflie::MotorData_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::crazyflie::MotorData_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace crazyflie

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::crazyflie::MotorData_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::crazyflie::MotorData_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::crazyflie::MotorData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "257e3dae15056b7e89ecd8c57477fe54";
  }

  static const char* value(const  ::crazyflie::MotorData_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x257e3dae15056b7eULL;
  static const uint64_t static_value2 = 0x89ecd8c57477fe54ULL;
};

template<class ContainerAllocator>
struct DataType< ::crazyflie::MotorData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "crazyflie/MotorData";
  }

  static const char* value(const  ::crazyflie::MotorData_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::crazyflie::MotorData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
int32 m1\n\
int32 m2\n\
int32 m3\n\
int32 m4\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::crazyflie::MotorData_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::crazyflie::MotorData_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::crazyflie::MotorData_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::crazyflie::MotorData_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.m1);
    stream.next(m.m2);
    stream.next(m.m3);
    stream.next(m.m4);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct MotorData_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::crazyflie::MotorData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::crazyflie::MotorData_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "m1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.m1);
    s << indent << "m2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.m2);
    s << indent << "m3: ";
    Printer<int32_t>::stream(s, indent + "  ", v.m3);
    s << indent << "m4: ";
    Printer<int32_t>::stream(s, indent + "  ", v.m4);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CRAZYFLIE_MESSAGE_MOTORDATA_H

